# Generated by Django 6.0.3 on 2026-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tareas_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
