# Generated by Django 6.0.3 on 2026-04-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tareas_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='done',
        ),
    ]
