# Generated by Django 6.0.3 on 2026-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_remove_tareas_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
    ]
