# Generated by Django 6.0.3 on 2026-04-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_nomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='fecha_ingreso',
        ),
    ]
