# Generated by Django 6.0.3 on 2026-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_remove_nomina_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena_hasheada', models.CharField(max_length=255)),
            ],
        ),
    ]
