# Generated by Django 6.0.3 on 2026-06-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_accesosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
